# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run on architecture
        # You may pin to the exact commit or the version.
        # uses: uraimo/run-on-arch-action@14a6e484f2ca4ca85252f01371b1edf0d8c90b41
        uses: uraimo/run-on-arch-action@v2.0.9
        with:
          # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          arch: aarch64 # optional, default is aarch64
          # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, buster, stretch, jessie, fedora_latest, alpine_latest, archarm_latest.
          distro: ubuntu20.04 # optional, default is ubuntu18.04
          # Shell commands to execute in the container.
          run: |
            uname -a
